Fix usage of http response body
Since https://github.com/esphome/esphome/pull/14966, usage of json body
response triggered a binding reference error:
> error: binding reference of type 'std::__cxx11::basic_string<char>&' to 'const std::__cxx11::basic_string<char>' discards qualifiers

The attached reproducer show a minimal example.

This commit does a similar correction than https://github.com/esphome/esphome/pull/15814