esp32_ble_beacon: enable CONFIG_BT_BLE_42_FEATURES_SUPPORTED
ESP-IDF does not enable CONFIG_BT_BLE_42_FEATURES_SUPPORTED by default
for the ESP32-C3 and ESP32-S3. This causes the following linker error
with esp32_ble_beacon:

/config/.esphome/platformio/packages/toolchain-riscv32-esp@11.2.0+2022r1/bin/../lib/gcc/riscv32-esp-elf/11.2.0/../../../../riscv32-esp-elf/bin/ld: .pioenvs/bug/src/esphome/components/esp32_ble_beacon/esp32_ble_beacon.o: in function `esphome::esp32_ble_beacon::ESP32BLEBeacon::gap_event_handler(esp_gap_ble_cb_event_t, esp_ble_gap_cb_param_t*)':
/config/.esphome/build/bug/src/esphome/components/esp32_ble_beacon/esp32_ble_beacon.cpp:164: undefined reference to `esp_ble_gap_start_advertising'
/config/.esphome/platformio/packages/toolchain-riscv32-esp@11.2.0+2022r1/bin/../lib/gcc/riscv32-esp-elf/11.2.0/../../../../riscv32-esp-elf/bin/ld: .pioenvs/bug/src/esphome/components/esp32_ble_beacon/esp32_ble_beacon.o: in function `esphome::esp32_ble_beacon::ESP32BLEBeacon::ble_setup()':
/config/.esphome/build/bug/src/esphome/components/esp32_ble_beacon/esp32_ble_beacon.cpp:151: undefined reference to `esp_ble_gap_config_adv_data_raw'

Enable CONFIG_BT_BLE_42_FEATURES_SUPPORTED to fix this.

Signed-off-by: Stijn Tintel <stijn@linux-ipv6.be>