Use correct return type
Use int32_t instead of int which is the actual type of arg.int_array.
This fixes a compiler error when trying to build for ESP32-C3:
Compiling .pioenvs/esp_c3/src/esphome/components/api/user_services.cpp.o
src/esphome/components/api/user_services.cpp: In function 'T esphome::api::get_execute_arg_value(const esphome::api::ExecuteServiceArgument&) [with T = std::vector<long unsigned int>]':
src/esphome/components/api/user_services.cpp:19:14: error: could not convert 'arg.esphome::api::ExecuteServiceArgument::int_array' from 'vector<long int>' to 'vector<long unsigned int>'
   return arg.int_array;
          ~~~~^~~~~~~~~
*** [.pioenvs/esp_c3/src/esphome/components/api/user_services.cpp.o] Error 1