Include vector header explicitly
It seems this header might be missing when using the latest Arduino
ESP32 version, leading to a compile time error:
In file included from src/esphome/components/uart/uart_esp32.cpp:2:
src/esphome/components/uart/uart.h:70:31: error: 'vector' in namespace 'std' does not name a template type
   void write_array(const std::vector<uint8_t> &data) { this->write_array(&data[0], data.size()); }
                               ^~~~~~
src/esphome/components/uart/uart.h:70:26: note: 'std::vector' is defined in header '<vector>'; did you forget to '#include <vector>'?
src/esphome/components/uart/uart.h:6:1:
+#include <vector>