Rename UART_PARITY_EN to avoid conflicts with ESP-IDF
It seems that UART_PARITY_EN is defined in the Arduino ESP32 SDK in
tools/sdk/esp32c3/include/soc/esp32c3/include/soc/uart_reg.h. With
the new SDK, when compiling for ESP32-C3 it seems that this header
file gets included causing expansion of UART_PARITY_EN which leads
to a compile error.
In file included from /root/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32c3/include/hal/include/hal/touch_sensor_types.h:19,
                 from /root/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32c3/include/esp_hw_support/include/esp_sleep.h:20,
                 from /root/.platformio/packages/framework-arduinoespressif32/cores/esp32/esp32-hal.h:33,
                 from /root/.platformio/packages/framework-arduinoespressif32/cores/esp32/HardwareSerial.h:51,
                 from src/esphome/components/uart/uart.h:4,
                 from src/esphome/components/uart/uart_esp32.cpp:2:
/root/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32c3/include/soc/esp32c3/include/soc/soc.h:85:34: error: expected unqualified-id before numeric constant
 #define BIT(nr)                 (1UL << (nr))
                                  ^~~
/root/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32c3/include/soc/esp32c3/include/soc/uart_reg.h:788:26: note: in expansion of macro 'BIT'
 #define UART_PARITY_EN  (BIT(1))
                          ^~~
src/esphome/components/uart/uart_esp32.cpp:15:23: note: in expansion of macro 'UART_PARITY_EN'
 static const uint32_t UART_PARITY_EN = 1 << 1;
                       ^~~~~~~~~~~~~~# Please enter the commit message for your changes. Lines starting

Side step the issue by using UART_PARITY_ENABLE instead of UART_PARITY_EN.