Use size_t for length parameter
The function uses this signature:
  esp_err_t nvs_get_blob(nvs_handle handle, const char* key, void* out_value, size_t* length);

So we can avoid those errors/warnings.

Compiling .pioenvs/esp_demo_s2/src/esphome/core/preferences.cpp.o
src/esphome/core/preferences.cpp: In member function 'bool esphome::ESPPreferenceObject::load_internal_()':
src/esphome/core/preferences.cpp:258:78: error: invalid conversion from 'uint32_t*' {aka 'long unsigned int*'} to 'size_t*' {aka 'unsigned int*'} [-fpermissive]
   esp_err_t err = nvs_get_blob(global_preferences.nvs_handle_, key, nullptr, &actual_len);
                                                                              ^~~~~~~~~~~
In file included from src/esphome/core/preferences.cpp:12:
/.../.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32c3/include/nvs_flash/include/nvs.h:455:87: note:   initializing argument 4 of 'esp_err_t nvs_get_blob(nvs_handle_t, const char*, void*, size_t*)'
 esp_err_t nvs_get_blob(nvs_handle_t handle, const char* key, void* out_value, size_t* length);
                                                                               ~~~~~~~~^~~~~~
src/esphome/core/preferences.cpp:267:72: error: invalid conversion from 'uint32_t*' {aka 'long unsigned int*'} to 'size_t*' {aka 'unsigned int*'} [-fpermissive]
   err = nvs_get_blob(global_preferences.nvs_handle_, key, this->data_, &len);
                                                                        ^~~~
In file included from src/esphome/core/preferences.cpp:12:
/.../.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32c3/include/nvs_flash/include/nvs.h:455:87: note:   initializing argument 4 of 'esp_err_t nvs_get_blob(nvs_handle_t, const char*, void*, size_t*)'
 esp_err_t nvs_get_blob(nvs_handle_t handle, const char* key, void* out_value, size_t* length);
                                                                               ~~~~~~~~^