ledc: check SOC_LEDC_SUPPORT_APB_CLOCK
Check if SOC_LEDC_SUPPORT_APB_CLOCK is defined instead of hardcoding the
default clock source for the LEDC peripheral to APB_CLOCK.

Fixes the following compile error on boards that don't have
SOC_LEDC_SUPPORT_APB_CLOCK (like the ESP32-H2 or ESP32-C6).

src/esphome/components/ledc/ledc_output.cpp: In function 'esp_err_t esphome::ledc::configure_timer_frequency(ledc_mode_t, ledc_timer_t, ledc_channel_t, uint8_t, uint8_t&, float)':
src/esphome/components/ledc/ledc_output.cpp:20:21: error: 'LEDC_USE_APB_CLK' was not declared in this scope; did you mean 'LEDC_USE_XTAL_CLK'?
   20 | #define DEFAULT_CLK LEDC_USE_APB_CLK
      |                     ^~~~~~~~~~~~~~~~
src/esphome/components/ledc/ledc_output.cpp:76:24: note: in expansion of macro 'DEFAULT_CLK'
   76 |   timer_conf.clk_cfg = DEFAULT_CLK;
      |                        ^~~~~~~~~~~

Signed-off-by: Stijn Tintel <stijn@linux-ipv6.be>