fix compile error for idf projects
getting:
```
src/esphome/components/json/json_util.cpp: In function 'std::__cxx11::string esphome::json::build_json(const json_build_t&)':
src/esphome/components/json/json_util.cpp:24:61: error: 'MALLOC_CAP_DEFAULT' was not declared in this scope
   const size_t free_heap = heap_caps_get_largest_free_block(MALLOC_CAP_DEFAULT) - 2048;
                                                             ^~~~~~~~~~~~~~~~~~
src/esphome/components/json/json_util.cpp:24:61: note: suggested alternative: 'MALLOC_ALIGNMENT'
   const size_t free_heap = heap_caps_get_largest_free_block(MALLOC_CAP_DEFAULT) - 2048;
                                                             ^~~~~~~~~~~~~~~~~~
                                                             MALLOC_ALIGNMENT
src/esphome/components/json/json_util.cpp:24:28: error: 'heap_caps_get_largest_free_block' was not declared in this scope
   const size_t free_heap = heap_caps_get_largest_free_block(MALLOC_CAP_DEFAULT) - 2048;
                            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```
the reason is the missing include of esp_heap_caps.h